### ISSUE TITLE
Rewrite trips

### ISSUE THREAD

**Issue by thisismeonmounteverest** [BeWelcome/rox#1]
Trips are a nice idea but unfortunately don't match with the community expectations.

There is a trips rewrite going on in a branch:
https://github.com/BeWelcome/rox/tree/feature/trips

Feel free to test on [https://api.bewelcome.org](https://api.bewelcome.org)

**Comment by tjadowski** [comment]
What kind of fixes (or refactoring) this rewrite trips need? Could you provide me some background? And desired result?

**Comment by thisismeonmounteverest** [comment]
Have a look at the TripController in src/Controller to get an idea; there's also a commented out section in landing.html.twig that should show people travelling in your area which makes/should make use of the new trips.

Additional requirements:
- As a user I want to be able to create, update and delete a trip which should be a collection of locations with a duration of stay and if a possibility to tell other members that I'm looking for a host or a meetup
- As a user I want to see travelers coming to my area and be able to send a request if I they are looking for a host

**Comment by tjadowski** [comment]
There are some member in test database where I can look how this trips feature works?

**Comment by thisismeonmounteverest** [comment]
Closing as trips rewrite has been released last year already.
