### ISSUE TITLE
Some regions' names don't get displayed in country pages

### ISSUE THREAD

**Issue by Railslide** [BeWelcome/rox#10]
For some regions, it shows only `([num])` instead of `[region name]([num])` 

Examples:
- [Serbia](http://www.bewelcome.org/places/Serbia/RS)
- [Kosovo](http://www.bewelcome.org/places/Kosovo/XK)

**Comment by lantti** [comment]
Looking at the testing database that seems to happen when a member is living in a place that has no admin1 area (region) connected to it. The reason that there are several such lines seems to be that there are several different ways how a place is left without an admin1 link. Some places have their admin1 field set to "00" and some to "" for example. These would show as different regions as the code responsible for printing out these lines expects every admin1 field to be valid, but they have no name as those fields are in fact invalid and the query for the region name obviously results empty.

The code responsible for including these "non-regions" in the statistics is in build/places/places.model.php, lines 435-458 (at least in the development branch of the code)

A quick and dirty fix would be to add a check for removing "non-regions" from the results the same way as regions without members are removed in the same function.

**Comment by Railslide** [comment]
What would happen to those members without a region (e.g. those 5 in Serbia)? Are they already counted somewhere else? Or will they just not be displayed in country pages?

**Comment by lantti** [comment]
Assuming that the country fields for all places are valid (and I didn't find any examples where they weren't) those members would still be correctly counted on the all countries page. This means that the information shown of the all countries page and some individual country pages would be inconsistent. A better fix would of course be going through the database and fixing the invalid region links if somebody is able to do this.

**Comment by lantti** [comment]
Ok, skip that last sentence. There seems to be no easy source for what place belongs to which region. At least geonames don't know them all either. So better just make our code tolerant to the fact that regions are sometimes inconsistent.

**Comment by lantti** [comment]
I wrote a quick patch and included it in the pull request #9 
I just removes the "non-regions" from the results. That also makes all members that live in a place without a valid region link inaccessible through browsing (they can still be found by map search). Not very nice for them, but I can't be bothered to come up with a better solution right now.

**Comment by amnesiac84** [comment]
The specific examples show a positive result, I therefore close this issue
