### ISSUE TITLE
[Stats] Statistics are wrong

### ISSUE THREAD

**Issue by amnesiac84** [BeWelcome/rox#102]
While following https://www.bewelcome.org/stats for some days I've noticed that the dates change, but the numbers don't.

For example, a week ago the number of logins peaked ~320 on April 20th...
Now it peaks at April 30th

Also, the title of the last 2 stats both say 'How many messages sent per day?'

**Comment by thisismeonmounteverest** [comment]
I activated the cron job to keep the statisitics up-to-date. Please keep an eye on them.

**Comment by amnesiac84** [comment]
They don't seem to update

**Comment by amnesiac84** [comment]
Unfortunately they are still not updated. If there's no quick fix, maybe it's better to take out the link to this page for the time being? No info is better than wrong info

**Comment by thisismeonmounteverest** [comment]
The daily ones are updating. I need to check what's wrong with the weekly overview.

**Comment by thisismeonmounteverest** [comment]
I just checked and the weekly one look correct as well. I also checked the transferred data and that is matching as well.

Maybe the scale at the bottom for the all time stats is confusing?

**Comment by crumbking** [comment]
I close this one. Seems to update now. Some peaks since a few days ;-)
Anyway there are stats which don't have any insights and just confuse.  Also the scale could be better here and there. If there is some time we can open an enhancement issue.
