### ISSUE TITLE
[Search] 404 when searching for a place (not logged in)

### ISSUE THREAD

**Issue by fequerver** [BeWelcome/rox#104]
As soon as I typed the place and clicked on ">" button on home screen I got the 404.
Link:
https://www.bewelcome.org/search/map?location=Curitiba%2C+Paran%C3%A1%2C+Brazil&updateMap=&keywords=&location_geoname_id=3464975&location_latitude=-25.4277800&location_longitude=-49.2730600&showOnMap=&ne_latitude=&ne_longitude=&sw_latitude=&sw_longitude=&accommodation_anytime=1&accommodation_dependonrequest=1&accommodation_neverask=1&inactive=1&showmap=1&min_age=&max_age=&gender=&can_host=1&order=6&items=20&distance=100&_token=KA6Ja8754QTV90k3PjnjIyP0lh_JxQW-Qiw42SwCRTg

**Comment by amnesiac84** [comment]
On the landing page, if you search at the bottom, you'll be redirected to **'/search/map?'**

I think it should redirect to **'/search/members?'** instead. Couldn't find the settings to change it though.

**Comment by thisismeonmounteverest** [comment]
@amnesiac84: /search/map is correct as this is only valid when you're not logged in.

@fequerver: I thought I found the root cause but unfortunately this is trickier to fix than expected.

Thanks for reporting, though.
