### ISSUE TITLE
[Groups] Unable to change group description

### ISSUE THREAD

**Issue by amnesiac84** [BeWelcome/rox#105]
I can't update the group descriptions where I'm administrator. It says updated, but doesn't seem to update

**Comment by thisismeonmounteverest** [comment]
@amnesiac84 This is likely the good old problem that no one other than the original creator can change the description or is that you?

**Comment by thisismeonmounteverest** [comment]
This should be fixed on beta now.

**Comment by crumbking** [comment]
Tested on live site. Seems to be fixed. closing
