### ISSUE TITLE
[Words] Bite-sized issue: clarify the wording to let hosts know they can drag the cursor to set a more precise location on the map

### ISSUE THREAD

**Issue by nekohayo** [BeWelcome/rox#107]
On the new website, in https://www.bewelcome.org/setlocation, it says:

> Enter a city/village/etc. (and optionally a country or more details) and click on "Search location". Then scroll down to see the results, select your location and click on "Save location".

To make it more obvious, I think it's missing a little piece of text at the end, saying something like this (presuming my interpretation is correct):

> After setting the city, you can drag the orange location marker on the map to a more accurate location closer to your home. This will not affect the city you're classified in for search results.

**Comment by nekohayo** [comment]
Might also be worth Relabelling the "Update location" button in https://www.bewelcome.org/editmyprofile to "Update or refine my location".

**Comment by amnesiac84** [comment]
Thanks! Changed the first suggestion, still thinking about the second suggestion :)

**Comment by crumbking** [comment]
Closing.
