### ISSUE TITLE
migrations failing on some wordcodes

### ISSUE THREAD

**Issue by lantti** [BeWelcome/rox#11]
(I don't know if we are tracking issues now here or still on trac, so I put this on both. Sorry for the confusion, feel free to close the one that is wrong)

Some of the wordcodes that should be added by running migrations are already present in the words.sql database dump. This causes the migrations to fail. The workaround that I used to continue with my install was replacing the INSERT INTO queries in the tools/roxmigration/roxmigration.php/_writeWordCodeToDb() function with REPLACE INTO queries. This way the query succeeds even if there is already an identical wordcode in the database.

Should we make this change to the official code too? Is there a reason why we would like to have a fatal error instead of silent replacement in such a conflict between the existing wordcode and a migration? Or would it be better to fix the developer db dump instead?

**Comment by lantti** [comment]
The REPLACE INTO "fix" is now available with the pull request #9 
I still don't know if it can somehow cause a major catastrophe and data loss as I am total newbie with SQL, but hopefully someone knows and can tell me.

**Comment by thisismeonmounteverest** [comment]
Updated the fix a bit to show a warning message instead of silently overwrite the wordcode.
