### ISSUE TITLE
[Signup] Broken password hiding; broken bug form

### ISSUE THREAD

**Issue by robsdedude** [BeWelcome/rox#110]
I've signed up using a password that contains parentheses ("(") and ")"). In the summary step https://www.bewelcome.org/signup/4 the password was replaced with asterisks ("*") but the parentheses where left in place. I guess some escaping failed or so… I'll now chose a different password.

--

I then tried to submit this issue using https://www.bewelcome.org/about/feedback but it failed. The error shown was `{$words->get($error)}` which isn't really helpful ;)

Context: I chose "Fehler (Bug) melden" (means "report a bug") entered the text above the "--" omitted the mail address and checked "Ich benötige keine Antwort." (means "I don't need an answer").

**Comment by robsdedude** [comment]
It also breaks with many other characters like `[` and `-`.

Btw. the summary page shows "Muttersprache 6" (means "mother tongue 6"). Also not very verbose ;)

**Comment by thisismeonmounteverest** [comment]
You're right the reason why the parentheses were shown was a bogus regexp. Replaced the regexp with a number of * to fix this.

The second problem was that the code insisted on having an email address even if you checked no answer required.

Thanks for reporting. Both is now fixed.

**Comment by andrelaszlo** [comment]
@thisismeonmounteverest Came here to report this, seems to still be the case on bewelcome.org, but I suppose the change isn't deployed yet? :) Looked (quickly) but didn't find any info about which version is currently running etc.

**Comment by thisismeonmounteverest** [comment]
The footer has this information including a link to the repository with the given version.

The last deploy to www happened on 2019-11-19. beta.bewelcome.org has the current software (2020-05-17).

**Comment by andrelaszlo** [comment]
Thanks @thisismeonmounteverest :balloon:
