### ISSUE TITLE
[Hosting Status] Replacing "MAYBE" with a Hosting Interest Indicator ("H. I." Indicator)

### ISSUE THREAD

**Issue by amnesiac84** [BeWelcome/rox#122]
According to the discussions and vote in the General Assembly of 2019, it was decided to remove the "MAYBE" hosting status to keep only "YES" and "NO" and to add a Hosting Interest (H. I.) Indicator, which is a number between 1 and 10.

> Existing profiles would be automatically converted from MAYBE to YES with 4 on the scale, and YES set to 8, with a message to members inviting them to adjust the setting if they want.
> Hosts can opt to display their Hosting Interest setting on their profile and it would be shown when the setting was last updated.

**> The proposal for solving the issues is as follows:**
> 
> There will only be two settings based on the answer to the question "Do you offer accommodation and want to receive hosting requests, at least occasionally": YES or NO.
> 
> New members who choose YES are shown the following text:
> 
> "Welcome to the BeWelcome community and thank you for offering to host BeWelcome members! Members looking for hosts will now be able to see your profile in search results. We let you influence where in the list you will be shown and how likely you are to be contacted by indicating how interested you are in receiving hosting requests. You can update this setting at any time, or switch to "NO" if you want to receive more, fewer or no requests. If you wish, you can also display your Hosting Interest on your profile by ticking this box: [ ].
> 
> Please indicate on this scale how interested are you in receiving hosting requests:
> 
>     I am very interested   |10 | 9 | 8 | 7 | 6 | 5 | 4 | 3 | 2 | 1 |   I am currently not so interested
> 
> [Note: I tried to insert a better image of the scale here, but that didn't work]
> 
> "Last updated: YYYY/MM/DD" or "xx ago" indicates when the status was last updated.
> 
> When the "Hosting Interest" system ("HI" system) is introduced, two things will happen for existing members who are currently set to YES or to MAYBE:
> 
> 1. Their profiles are automatically set to the corresponding default settings on the scale, e.g. "8" for YES and "4" for MAYBE, with no need for them to take action unless they want to fine-tune it. This would leave two addtional  steps up for YES profiles and three steps up or down for MAYBE profiles.
> 
> 2. The hosting status MAYBE is consolidated with YES, with a default "HI" score of "4" which with the new algorithm will give essentially the same position in default search results as today.
> 
> 3. Members receive a notification and explanation of the new system encouraging them to check if they are happy with how their profiles are displayed in default search results and to make any desired adjustments.

**Comment by crumbking** [comment]
This should be fixed. We have a slider. Closing.
