### ISSUE TITLE
mother tongue shows as number on sign up review

### ISSUE THREAD

**Issue by guysoft** [BeWelcome/rox#129]
Hey,
So when you review your signup on on https://www.bewelcome.org/ You get Mother tongue showing up as a number.
Image of how it looks on the page:
![Screenshot_20200516_225146](https://user-images.githubusercontent.com/325670/82129031-8e9b0980-97c8-11ea-92ac-b825cae6d9ab.png)

**Comment by thisismeonmounteverest** [comment]
Hey,
Already fixed on beta.

Thanks for reporting, though.

**Comment by guysoft** [comment]
Is there a way to view the beta website?

**Comment by thisismeonmounteverest** [comment]
Yes, you can access it with your normal credentials using https://beta.bewelcome.org
