### ISSUE TITLE
[Security] Mixed content warnings (https)

### ISSUE THREAD

**Issue by simison** [BeWelcome/rox#13]
Hitting https://www.bewelcome.org/members/mikael to the browser works normally.

Opening that link (with `target="_blank"`) from another page breaks https and causes the page load without CSS.

Refreshing doesn't help but hitting enter at URL bar helps.

Chrome.

Log;

```
Mixed Content: The page at 'https://www.bewelcome.org/members/mikael' was loaded over HTTPS, but requested an insecure image 'http://www.bewelcome.org/gallery/thumbimg?id=15567'. This content should also be served over HTTPS.
mikael:489 Mixed Content: The page at 'https://www.bewelcome.org/members/mikael' was loaded over HTTPS, but requested an insecure image 'http://www.bewelcome.org/gallery/thumbimg?id=15568'. This content should also be served over HTTPS.
mikael:489 Mixed Content: The page at 'https://www.bewelcome.org/members/mikael' was loaded over HTTPS, but requested an insecure image 'http://www.bewelcome.org/gallery/thumbimg?id=15564'. This content should also be served over HTTPS.
mikael:489 Mixed Content: The page at 'https://www.bewelcome.org/members/mikael' was loaded over HTTPS, but requested an insecure image 'http://www.bewelcome.org/gallery/thumbimg?id=15562'. This content should also be served over HTTPS.
mikael:522 Mixed Content: The page at 'https://www.bewelcome.org/members/mikael' was loaded over a secure connection, but contains a form which targets an insecure endpoint 'http://www.bewelcome.org/a'. This endpoint should be made available over a secure connection.
```

**Comment by simison** [comment]
So the problem won't occur from jsfiddle: https://jsfiddle.net/1dev4h1s/1/ — but it does occur when I'm opening the link from a page served at http://localhost:3000/

```
<a href="https://www.bewelcome.org/members/mikael" target="_blank">test</a>
```

— weird!

**Comment by simison** [comment]
These might also affect:

```
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
        <html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en" xmlns:v="urn:schemas-microsoft-com:vml">
```

Recommend searching and replacing all `http://`'s from the codebase to `//`.

**Comment by simison** [comment]
BTW, the same stylesheets missing issue occurs when clicking the https link from finarfin's post: http://www.bewelcome.org/forums/s13127/#post73001

**Comment by thisismeonmounteverest** [comment]
After first investigations the issue seems to happen when you're already logged-in to BW and open a new window/tab on https://www.bewelcome.org/ with target="_blank".

**Comment by simison** [comment]
:+1: I'd just force all https. It's 2015 after all. ;-)

**Comment by simison** [comment]
@thisismeonmounteverest is this fixed yet?

**Comment by simison** [comment]
FYI, @trustroots got a report telling that even linking to BW's https version from our https page was broken. Didn't look more into it, but I'm switching back to linking http for now.

**Comment by simison** [comment]
FYI: [Chrome plans to start highlighting Not Secure websites](https://medium.servertastic.com/chrome-plans-to-start-highlighting-not-secure-websites-2babf35b46e6#.kiwzwz1zy)

![image](https://cloud.githubusercontent.com/assets/87168/18311374/99c5235a-750c-11e6-8bd9-42c6a0be365b.png)

**Comment by amnesiac84** [comment]
I think this has been fixed now with the new website, maybe except for images in old posts... Will close this issue unless someone contradicts my findings.

**Comment by beatnickgr** [comment]
I don't know if this is relevant, but clicking any BW link returns "Please login to view these pages" even if I'm logged in.
I must F5 in order to load the page.

**Comment by thisismeonmounteverest** [comment]
@beatnickgr: No, it is not. That is an issue that is hopefully fixed already with the latest changes to the login process. (Already deployed to alpha, in case you want to try.)

**Comment by alifeee** [comment]
this seems to still be happening, fwiw

recreation steps:

```bash
mkdir /tmp/bewelcome1410 && cd /tmp/bewelcome1410
echo '<a href="https://bewelcome.org/members/alifeee">alifeee</a>' > index.html
python -m http.server 8080
```

now visit <http://127.0.0.1:8080/> in your web browser (in my case firefox) and left/right click the URL. you will be led to the page without styles. I guess this is as mentioned above, the `Referer` is `http://127.0.0.1:8080/` which is `http` not `https`

**Comment by thisismeonmounteverest** [comment]
That happens as the link points a page rendered by the old code (whhich will vanish soon). If you want to avoid that either link to https://www.bewelcome.org or point to https://www.bewelcome.org/members/<username>/comments to start close to your profile.
