### ISSUE TITLE
No way to change newsletter preference?

### ISSUE THREAD

**Issue by amnesiac84** [BeWelcome/rox#133]
I haven't found a way to disable the newsletter. I know there used to be an option in the past (and we advertise it in the newsletters), but it may got lost in the website update.

Would be great to have that option and even greater to be able to (de)activate it with a direct link in the newsletters. But that's probably a longer term wish

**Comment by thisismeonmounteverest** [comment]
I changed the visibility of the forum sort order preference a few days ago and thought I reverted that back, but seems I hid the newsletter one instead :(

As soon as I have access to the database I hide the correct one.
