### ISSUE TITLE
Can't upload images to discussions http code 302 in post request

### ISSUE THREAD

**Issue by guysoft** [BeWelcome/rox#134]
Hey, when I try and upload images. I get the following error:
![Screenshot_20200520_100710](https://user-images.githubusercontent.com/325670/82416056-1c554e00-9a82-11ea-8770-1bf71f8ec3f5.png)

Inspecting the network console, I can see that the image POST method is returning http code 302:
![Screenshot_20200520_101009](https://user-images.githubusercontent.com/325670/82416105-3131e180-9a82-11ea-872b-a0d1b36e334c.png)

I can then keep writing the post and submit it, without the image.

Using Firefox 76.0.1 on Ubuntu 2020.04

**Comment by thisismeonmounteverest** [comment]
Hi guysoft,

Could you show me the response?

I assume the image was too big or something like that.

**Comment by guysoft** [comment]
Hey @thisismeonmounteverest It worked now. Closing, and reopening if it will show up again.
I have a feeling its because I am logged in to both bewelcome.org and beta.bewelcome.org. But will update if I get this again.
