### ISSUE TITLE
[Groups] Inviting members sends an invitation to the invitor

### ISSUE THREAD

**Issue by amnesiac84** [BeWelcome/rox#135]
I was inviting members to a closed group and received the invitation in my own inbox with them as sender.

They also received the invitation, so it's double sent

**Comment by thisismeonmounteverest** [comment]
Did you try beta? Because I rewrote most of the code and would like to know if I need to fix this before deploying on www. You can invite me :)

**Comment by amnesiac84** [comment]
"Sorry, inviting the member failed. Please try to reload the page and try again."

**Comment by thisismeonmounteverest** [comment]
I have a look tomorrow.

**Comment by crumbking** [comment]
Should be fixed. Closing
