### ISSUE TITLE
  Contact to shevek down /messages/compose/shevek  (regarding: Android Native Application)

### ISSUE THREAD

**Issue by wischweh** [BeWelcome/rox#136]
Hey guys,

the contact page to shevek is down:

Page not found
The page you tried to open (/messages/compose/shevek) doesn't exist.

I am an Android Lead considering starting an effort on a native Android App.

I have a vision of how this should be done, but don't know if this is compatible with how beWelcome thinks and works. And I would need a few more people on all kind of levels to help, also designers and people who are familiar with beWecome to make that work.

I am just new to beWelcome (One of those Couchsurfing Exilants) and don't know my way around yet. So I now try this way to get into contact. I have lots of questions regarding your plans for mobile apps.

**Comment by thisismeonmounteverest** [comment]
@wischweh: Thanks for the report, I fixed a few languages which still had old links for new message link. Maybe time for a redirect...

Please send a message now. You can also create a new group for app development if you like (probably better).
