### ISSUE TITLE
[Groups] Unable to invite members

### ISSUE THREAD

**Issue by amnesiac84** [BeWelcome/rox#142]
I can't invite new members into a (semi-closed) group: 
"Sorry, inviting the member failed. Please try to reload the page and try again."

**Comment by thisismeonmounteverest** [comment]
Isn't this the same issue as #135?

**Comment by amnesiac84** [comment]
no, that one was about who sends and who receives the invitation message... can't check if that's fixed already since I can't invite someone in the group

**Comment by thisismeonmounteverest** [comment]
#135 ends with I can't send :) But neither is fixed.
