### ISSUE TITLE
[FAQ] Can't create a new category, can't create a new FAQ

### ISSUE THREAD

**Issue by amnesiac84** [BeWelcome/rox#143]
I was trying to create a new category in FAQ, but the Wordcode showed a diabled (grey) text input, so I couldn't create one.

While trying to make a new FAQ under an existing category (https://www.bewelcome.org/admin/faqs/1/create), I got this error:
> "Unfortunately the server ran into an error and your request can't be fulfilled."

**Comment by thisismeonmounteverest** [comment]
Fixed on beta.

**Comment by crumbking** [comment]
@amnesiac84 Could you test on beta?

**Comment by crumbking** [comment]
Error on the following pages:
https://www.bewelcome.org/admin/faqs
https://www.bewelcome.org/admin/faqs/[numbers]

**Comment by thisismeonmounteverest** [comment]
@crumbking: I see the problem and should be able to fix that in the next five minutes :)
