### ISSUE TITLE
The link "home_updateMap" on the home open the search by user

### ISSUE THREAD

**Issue by nonno** [BeWelcome/rox#144]
Instead of opening a search by map, or a change location, the click on the user location in the home open the search by user.

![Screenshot 2020-05-25 at 22 13 37](https://user-images.githubusercontent.com/4105325/82841064-03f79000-9ed5-11ea-8104-6ddf75edd6e2.png)

**Comment by thisismeonmounteverest** [comment]
@nonno: Thanks for reporting this. I changed the routes in the code and probably deploy that tonight.

**Comment by thisismeonmounteverest** [comment]
Fixed on beta.

**Comment by crumbking** [comment]
Tested on beta. Fixed
