### ISSUE TITLE
Image url in pm can be guessed and seen by everyone

### ISSUE THREAD

**Issue by stijnhau** [BeWelcome/rox#145]
https://www.bewelcome.org/gallery/show/uploaded/479

Want a picture sent to me or so but all pm pioctures are vissible

**Comment by amnesiac84** [comment]
I think all pictures are visible on default (since they are gallery pictures on the profiles), but you have to be logged in to see them.

Not saying that they shouldn't have a harder to guess URL

**Comment by stijnhau** [comment]
Are they
Even if you send in pm?
Images in pm should never be visible to other users

**Comment by alexandrupd** [comment]
Yes, they are. Although it's my ugly face in that picture, I didn't send it. And I can see it. You can test this yourself by going backwards in the URL to https://www.bewelcome.org/gallery/show/uploaded/478 or https://www.bewelcome.org/gallery/show/uploaded/477 or https://www.bewelcome.org/gallery/show/uploaded/476 and so on.

**Comment by thisismeonmounteverest** [comment]
Regardless of where you use the CKEditor the upload uses the same endpoint, therefore all images are uploaded publicly for all members (the upload was actually added as a feature for the forums and groups).

The obviously easiest solution to fix that is to disallow adding images to pm/requests.

**Comment by crumbking** [comment]
Agree you can guess image urls. But you can't see them while logged out.

**Comment by thisismeonmounteverest** [comment]
Guessing urls even if you need to be logged in for this is basically bad.

I have a fix ready that will ask for a hash value out of image size and name along with the image id. So guessing will be that much harder...

**Comment by stijnhau** [comment]
That is a better idea.
But I even have better idea.
Isn't it a php function that returns the image?
Then we can add validation there to see if I'm sender or receiver of that pm

**Comment by thisismeonmounteverest** [comment]
@stijnhau That won't work as the uploaded image doesn't have that information that it is part of a PM.

**Comment by stijnhau** [comment]
But arent the images stored in the db and then show by id.
Then we can edd 2 extra colums like fk_field and fk_id and fk field needs to be pm in that case an fk_id the id of the pm.
Then we have all the data and we can fix that for new uploaded images.

**Comment by thisismeonmounteverest** [comment]
@stijnhau You're welcome to help developing :)
To the problem at hand: Yes, I can use a different URL to upload from the messages/requests CKEditor and store that information, but then I either use two database tables which means redundancy or clutter one with extra information.
The way I design it I can use one table, do not need to mess around with the editors in different places and the URLs are still not guessable.
Additionally my "fix" will deliver a placeholder image (just a grey image of the right dimensions) in case someone tries to access the file without being allowed (or with the wrong URL). Which is nicer with the email notifications.

**Comment by stijnhau** [comment]
it can still be stgored on the same location but that location should be outside of the public folder.
Youi can look at my assetManager system as an example.

**Comment by thisismeonmounteverest** [comment]
This is now fixed on beta with a uniqueID generated when the file is uploaded. Access using the old URL is still possible but will be discontinued after fixing the links in the messages.

**Comment by crumbking** [comment]
@stijnhau Could you test on beta.bewelcome.org?

**Comment by crumbking** [comment]
fixed with release
