### ISSUE TITLE
Wrong links in the "on page" translation

### ISSUE THREAD

**Issue by crumbking** [BeWelcome/rox#157]
I visited the landing page with German language. I switched translation "on" an checked missing ID's. I found one and clicked the "plus" button. The link forwards me to the "English edit page" of the ID. I would expect to be forwarded to the "German create page".

**Comment by gl0bi** [comment]
I am currently translating on beta.bewelcome.org and could not reproduce it.

**Comment by crumbking** [comment]
You are right. Not an issue anymore on beta and can't reproduce it on live page. As I manually edited the URL and translated the ID.
