### ISSUE TITLE
Activities near me on landing page not shown

### ISSUE THREAD

**Issue by crumbking** [BeWelcome/rox#159]
There is an activity near me (Leipzig) which should show up on the landing page to show me something is going on. Instead nothing is shown ...

![grafik](https://user-images.githubusercontent.com/1238326/83980785-c3f2cd00-a918-11ea-9a6b-380401b6941d.png)

**Comment by crumbking** [comment]
200 km

**Comment by crumbking** [comment]
The activities are shown but shouldn't there a indicator next to the activities tab? As we start with forum as default tab I have no reason to click on the activities tab. So I would miss some cool activities near me.

**Comment by thisismeonmounteverest** [comment]
@crumbking: That's weird, if the upcoming list isn't empty I'd expect a bagde to be shown next to 'Activities'.

**Comment by crumbking** [comment]
Okay I see the badge(3) now. I don't like the preference thought. We have enough of them all over the place :smile: (preference don't work, btw)
Simply default the 50km or another radius.

**Comment by thisismeonmounteverest** [comment]
@crumbking The preference will be hidden in the end I think. What preference that doesn't work are you talking about?

**Comment by crumbking** [comment]
There is a slider with label landing.activities.show.online. Fun part today on beta:
I see 3 activities but I'm informed via badge about 10. I have 200 km radius selected.

![grafik](https://user-images.githubusercontent.com/1238326/84818915-875d5a80-b017-11ea-8d50-134a4ffe5645.png)

**Comment by thisismeonmounteverest** [comment]
@crumbking: The 10 is a work-around for the issue that the landing page wasn't showing at all; which I hope I have fixed now.

That slider is working as expected there are just no online activities yet, so you might want to create one :)
