### ISSUE TITLE
[Volunteer] Add System Admin

### ISSUE THREAD

**Issue by amnesiac84** [BeWelcome/rox#162]
The BoD decided it would be good to have System Admin listed on the volunteer page: https://www.bewelcome.org/about/getactive

Following text should be included:

> If you are a GNU/Linux system administrator and like to build servers without relying on external providers, you are welcome to join the sysadmin team and let a community of more than 120.000 members profit from your volunteer work!

**Comment by crumbking** [comment]
Tested in beta. Fixed.
Thought the missing group with a dot looks strange. But a translation issue so I close this one.
