### ISSUE TITLE
Right menu override page

### ISSUE THREAD

**Issue by Tr4sK** [BeWelcome/rox#163]
Hey, on beta when I reduce horizontally my web browser, the right menu move over the thread list in a group or forum. Then, I am not able to click on the right part on the post (red arrow).

![threadlist](https://user-images.githubusercontent.com/1238195/84317297-d7967180-ab6c-11ea-8b2a-87776cff168a.png)

I have a normal screensize but love to split thing on my screen.

**Comment by thisismeonmounteverest** [comment]
@Tr4sK: I can't reproduce this. Which browser? And which page :)

**Comment by Tr4sK** [comment]
@thisismeonmounteverest you can reproduce this by resizing the horizontal size of your windows.

**Comment by thisismeonmounteverest** [comment]
No, I can't :)

**Comment by Tr4sK** [comment]
I cannot reproduce this everywhere. But the same bug appear in chromium and Firefox

Buggy : https://www.bewelcome.org/group/570/forum
Not buggy: https://www.bewelcome.org/group/139/forum

Buggy: https://www.bewelcome.org/forums/page1/page2/
Not buggy: https://www.bewelcome.org/forums/page1/page1/
Not buggy: https://www.bewelcome.org/forums/page1/page3/

**Comment by crumbking** [comment]
I believe it is in both buggy pages a thread in the bug group. The issue is thread title. The long translation ID does not break. So the threaded view (the table) breaks out on the right. Solution could be to break long words in thread title to not break the box. 

That is the thread:
https://beta.bewelcome.org/group/570/forum/s20956-request_error_numberoftravellers_empty_shown_as_ID

**Comment by crumbking** [comment]
Same thing happened with long (not breaking usernames) We should force the break if space to small.

**Comment by Tr4sK** [comment]
@thisismeonmounteverest what do you mean by partially ?

**Comment by Tr4sK** [comment]
It is fixed on my side anyway. Thank you

**Comment by thisismeonmounteverest** [comment]
@Tr4sK It's only partly fixed as I made the table responsive which means if it overflows you need to scroll to get to the >.
