### ISSUE TITLE
Translation of date (last post) does not work on group overview lists

### ISSUE THREAD

**Issue by crumbking** [BeWelcome/rox#171]
d F Y seems not be translated.
https://github.com/BeWelcome/rox/blob/cce2293489e8c3dccd995697a79ae992c886975d/build/groups/templates/groupsdisplay.php#L26

Relevant pages:
https://www.bewelcome.org/groups/search
https://www.bewelcome.org/groups/mygroups

**Comment by thisismeonmounteverest** [comment]
@crumbking Removed the localization attempt for the date and replaced it with iso date format.

**Comment by crumbking** [comment]
Fixed
