### ISSUE TITLE
Can't rename account / feedback form not working

### ISSUE THREAD

**Issue by NightTsarina** [BeWelcome/rox#173]
Hi,

I am sorry to use the bug tracker for this, but I don't know what else to try. I have sent many support requests (as indicated in the [FAQ](https://www.bewelcome.org/about/faq/5#question2)) and nobody has ever replied to me. I am creating this bug in hopes that some fellow techie might give me a hand.

I am trans and changed my name and nickname everywhere over a year ago. Sometimes account usernames can't be changed, but they are not usually shown. In beWelcome, the username appears **all the time**, and that is very distressing.

My username (Tincho) is a very gendered nickname that I used to use everywhere (I was @TheTincho in github), and it hurts me that it still appears in many places, so unless I can change it, I will have to delete my account.

So, pretty please, can somebody give me a hand?

And more generally, is there anyone taking care of replying to support requests?

Thanks.

**Comment by thisismeonmounteverest** [comment]
@NightTsarina Support is currently rather overrun and while the number of volunteers is the same the number of requests is rather high now.
Please send a message through BeWelcome to shevek so that we know this is a genuine request.

**Comment by NightTsarina** [comment]
> @NightTsarina Support is currently rather overrun and while the number of volunteers is the same the number of requests is rather high now.
> Please send a message through BeWelcome to shevek so that we know this is a genuine request.

Hi @thisismeonmounteverest , thank you very much for your quick reply!

I have just sent a message to shevek as instructed.

About support being overrun, I completely understand that. But I have to point out that I have sent requests well before the CS crisis. I think it would be good UX to add some automated acknowledgement email and some way to track support requests already sent; right now it is just a black box for the user.

**Comment by amnesiac84** [comment]
I hope shevek can change the account name.

It's not that support is being overrun. Actually due to many new volunteers it has been cleaned up as never before. However, there's still a big issue that not all mails sent are processed in the software we use. It's a bug beyond the development team I think. This needs a bigger priority and will write the BoD right away
