### ISSUE TITLE
Email notifications with unmerged placeholders

### ISSUE THREAD

**Issue by NightTsarina** [BeWelcome/rox#174]
Hi,

I have just received an email notification of a direct message, with this repeated greeting, including an unmerged placeholder, plus using the username instead of the visible name:

** text/plain part, note the invalid markup **
```
[![](cid:@images/logo_index_top.png)](https://www.bewelcome.org/) Dear %Tincho%,

 Dear Tincho,
```
** text/html part, with markup removed **
```
Dear %Tincho%,
        Dear Tincho,
```

**Comment by thisismeonmounteverest** [comment]
@NightTsarina All communication through bewelcome uses the username only.

The duplicate greeting will be removed in the near future as soon as the tests on beta have finished.

**Comment by NightTsarina** [comment]
Additional info: In the last few notifications I did not get the duplicated greeting, but the username is still surrounded by percent signs.

**Comment by thisismeonmounteverest** [comment]
@NightTsarina This should be fixed now. Could you please confirm?

**Comment by NightTsarina** [comment]
Can you send me a DM or something? I don't think I can force the system to send me a notification

**Comment by NightTsarina** [comment]
Notification arrived, all looks good. Thanks!
