### ISSUE TITLE
[Signup] Specific e-mail address didn't work

### ISSUE THREAD

**Issue by amnesiac84** [BeWelcome/rox#175]
Someone tried to sign up with an e-mail address containing a (lower case) initial, followed by a dot and a last name starting with an upper case last name, for example:

**m.Yname@provider.bw**

The person could go through to the last phase of signing up, but after submitting the data, the radio buttons were cleared and nothing else happened.

After trying to create the account with given e-mail address, I have tried another address which then worked, so it was definitely the address that bugged the signing up process

**Comment by thisismeonmounteverest** [comment]
@amnesiac84 Finally helpful input :)
Fixed on beta and www. 
The email address was turned into lowercase but the confirmation stayed untouched. The compare therefore failed.
