### ISSUE TITLE
Czech translations are broken

### ISSUE THREAD

**Issue by 12people** [BeWelcome/rox#177]
There are several severe issues with the translation system for the Czech language:

1. All pages show up as having "0 existing translations" and a full set of "fallback translations", even when the whole page is translated: https://jumpshare.com/v/sp6bkN0QuF6qZkCOdOEz
2. Some translated strings don't show up in the UI at all: https://jmp.sh/ilEkiVw . It seems impossible to translate core items like menubar items or homepage content.
3. Even when a string is translated, the translation doesn't even show up in the list of fallback translations.

**Comment by thisismeonmounteverest** [comment]
@12people: Thanks for reporting. This is fixed on https://beta.bewelcome.org now. Please let me know if this works for you then I move the missing files to www.

**Comment by 12people** [comment]
Awesome, seems to work!

Just one bug that I found – the landing.activities.show.online string seems to be missing:
<img width="660" alt="image" src="https://user-images.githubusercontent.com/7361228/86406609-b7f9f100-bcb3-11ea-9ca5-c38b61d89e54.png">

**Comment by 12people** [comment]
Also, I'm wondering -- perhaps the same bug affects other languages as well. Have you checked whether other languages are also affected?

**Comment by 12people** [comment]
@thisismeonmounteverest could you move the files over to the stable website?

**Comment by 12people** [comment]
@thisismeonmounteverest Just wondering when I can expect this on the stable site.

**Comment by thisismeonmounteverest** [comment]
@12people I plan to update the stable site tomorrow around noon.

**Comment by 12people** [comment]
Oh wow, awesome, thanks for the update! :)
