### ISSUE TITLE
Delete profile redirects to "Page not found"

### ISSUE THREAD

**Issue by hebinzin** [BeWelcome/rox#182]
At the [delete profile page](https://www.bewelcome.org/deleteprofile), whenever I click the "delete profile" buttom I'm presented with this:

"Page not found

Hi _username_,

Unfortunately the server ran into an error and your request can't be fulfilled.
Return to the homepage."

**Comment by hebinzin** [comment]
Checking later, the account was removed nonetheless.

**Comment by thisismeonmounteverest** [comment]
@hebinzin That is a known bug on www the code tried to remove your username from a table that was removed during the rewrite.

Doesn't happen anymore on beta but that's probably not of an interest to you anymore :)

**Comment by hebinzin** [comment]
Kind of you to let me know. Thanks for replying!
