### ISSUE TITLE
[Docker] Some Member fields are not properly saved from profile form

### ISSUE THREAD

**Issue by vincentchalamon** [BeWelcome/rox#187]
For example: firstName

**Comment by thisismeonmounteverest** [comment]
@vincentchalamon: I fixed the first name field issue with https://github.com/BeWelcome/rox/commit/57fc823b240de5c29a8d1be4b38c535851f4e022.

Any other fields you're aware of?

**Comment by vincentchalamon** [comment]
Haven't found other fields with this issue
