### ISSUE TITLE
"Ugly" title in progressive WebApp launch screen 

### ISSUE THREAD

**Issue by nonno** [BeWelcome/rox#191]
I've been using the progressive web app on my Android phone for some time (Pixel 3a - Android 11), and each time I feel a bad sensation reading the title `BeWelcome Progressive Web App`. Is it really needed to explain in the title that it's a progressive web app? I would bet that the 99.9% of the users don't know what that means, and it doesn't provide any value.
It could be a good idea to write just BeWelcome, or if you think that the logo is famous enough, probably the title could be left also empty (with only the logo that launch screen is very neat).
Just an opinion, but I waited more than two weeks and I always have the same impression :) 

https://github.com/BeWelcome/rox/blob/228ca92237445d69338274af1ba732d4e09abbbf/public/manifest.webmanifest#L4

![Screenshot_20201014-172124](https://user-images.githubusercontent.com/4105325/96010472-1baec100-0e42-11eb-9cba-28c03235c73d.png)

**Comment by crumbking** [comment]
I followed your suggestion and mark it as fixed.
