### ISSUE TITLE
"Column name `id` referenced for relation from App\Entity\AlternateLocation towards App\Entity\Location does not exist" error

### ISSUE THREAD

**Issue by DaveLomber** [BeWelcome/rox#192]
When I ran

`php bin/console test:database:create --drop --force`

getting

`Column name `id` referenced for relation from App\Entity\AlternateLocation towards App\Entity\Location does not exist.`

Could someone please help me get the root cause 

Thanks

**Comment by thisismeonmounteverest** [comment]
@DaveLomber: Sorry, for the inconvenience. There is a fix already but it was done in a pull request which was expected to be merged quickly but is currently stalled.

Please change the file given here: https://github.com/BeWelcome/rox/pull/184/commits/047c609d3e2ecb9c84daf24e497162d0919b3eee

**Comment by DaveLomber** [comment]
@thisismeonmounteverest thanks 
it works this way

**Comment by crumbking** [comment]
close as fixed
