### ISSUE TITLE
Strange page when opening closed threads

### ISSUE THREAD

**Issue by amnesiac84** [BeWelcome/rox#194]
In some groups, some of the discussions are hidden when you're not a member of the group. Apparent public group threads are clickable for every member, for example in the [Istanbul Group](https://www.bewelcome.org/group/104)

However, clicking on a thread in that group that apparently is open for all members returns a strange page with no text and only a menu, for example here: [https://www.bewelcome.org/group/104/forum/s21867-Looking_for_host_in_Istanbul](https://www.bewelcome.org/group/104/forum/s21867-Looking_for_host_in_Istanbul)

**Comment by crumbking** [comment]
@amnesiac84 I hope this is fixed. Should be already released. Closing. Feel free to reopen if needed.
