### ISSUE TITLE
Missing text: "polls_no_polls"

### ISSUE THREAD

**Issue by Gerwanese** [BeWelcome/rox#213]
URL: https://www.bewelcome.org/polls (as well as https://beta.bewelcome.org/polls)

Placeholder "polls_no_polls" is shown and should probably show a proper text instead. To make sure that this text isn't intended in the English version, I changed language to German and the same placeholder is shown.

![grafik](https://user-images.githubusercontent.com/17579552/105649275-dcb3f100-5eaf-11eb-8490-9edd5e2d31bd.png)

Disclaimer:
This is my first bug report; please let me know if I did anything wrong so I can improve in the future.
I'll post a second bug with similar problem as well but on a different site - just in case, to make it easier to fix them separately.

**Comment by thisismeonmounteverest** [comment]
@Gerwanese Thanks for reporting I added the translation on www, next time someone translates English on beta, it should be visible there as well.
