### ISSUE TITLE
Several missing texts on preferences page

### ISSUE THREAD

**Issue by Gerwanese** [BeWelcome/rox#214]
URL: https://www.bewelcome.org/mypreferences (and https://beta.bewelcome.org/mypreferences)

In the "Website" section of preferences the last three options lack proper labels and also "?" tooltips but instead just show placeholders.
![grafik](https://user-images.githubusercontent.com/17579552/105649474-be9ac080-5eb0-11eb-913d-c6437378bdaf.png)

This is the same type of issue as reported in #213 so depending on organisation they might be solved together.

**Comment by thisismeonmounteverest** [comment]
@Gerwanese Added the missing translatable items.
