### ISSUE TITLE
Dead menu link "BeWelcome Forum Wiki"

### ISSUE THREAD

**Issue by Gerwanese** [BeWelcome/rox#215]
How to reproduce:
1. go to your profile (https://www.bewelcome.org/members/<username>)
2. go to "Forum Posts" (right side menu, last item, URL https://www.bewelcome.org/forums/member/<username>)
3. click on "BeWelcome Forum Wiki" (right side menu), which will try to open https://www.bewelcome.org/about/faq/6
![grafik](https://user-images.githubusercontent.com/17579552/105649821-eb9ba300-5eb1-11eb-96d5-7fa158e2f4f1.png)

Issue verified on beta website as well.

//Update: Alternative way to get there:
1. "Community" on the top menu
2. "Discussions" will bring you to https://www.bewelcome.org/forums
3. as above

**Comment by thisismeonmounteverest** [comment]
@Gerwanese Fixed. Thanks for the pointer.
