### ISSUE TITLE
Dead menu link "Wiki Doc" on polls page

### ISSUE THREAD

**Issue by Gerwanese** [BeWelcome/rox#217]
Polls page: https://www.bewelcome.org/polls
Click on "Wiki Doc" in the right side menu (URL: https://www.bevolunteer.org/wiki/How_pollsworks)
![grafik](https://user-images.githubusercontent.com/17579552/105652087-c5c5cc80-5eb8-11eb-9762-27eab997d064.png)

As the wiki currently seems to undergo renovation, fixing this bug might need to be delayed until a new wiki site for polls exists (or the menu link might simply be removed for the time being).

**Comment by thisismeonmounteverest** [comment]
@gerwanese: That link is simply pointing to the wrong wiki... that should be an easy fix for someone starting with the code, so I put a label to it.

**Comment by thisismeonmounteverest** [comment]
I fixed it myself now in the code. Will still take a while to be deployed.
