### ISSUE TITLE
Docker: geolocalization not working

### ISSUE THREAD

**Issue by Jesus82** [BeWelcome/rox#221]
Hi, right now geolocalization doesn't work anywhere when testing with Docker, and that makes some pages unreachable in local. Would there be a way to fix this? Thanks in advance!

**Comment by thisismeonmounteverest** [comment]
@Jesus82: There are only two location in the test database: Berlin and Jayapura.

If you want more: `make install-geonames` That will download the full dump from geonames and should fix that problem.
