### ISSUE TITLE
Missing error message on sign-up

### ISSUE THREAD

**Issue by gbenouville** [BeWelcome/rox#222]
If you sign up and choose the "yes" option for accommodation but leave the hosting interest indicator to 0, it displays "SignupErrorProvideHostingInterest" instead of a nice English message. Need to create a wordcode I suppose.

**Comment by thisismeonmounteverest** [comment]
I created the wordcode but there is still something off. If you select 'Yes' and nothing before clicking on 'Next>>' else the error message isn't shown (but all others are). But when everything else is in order but that the message is now shown, so I guess that fix can wait till the rewrite.
