### ISSUE TITLE
[Signup] Not so visible error message

### ISSUE THREAD

**Issue by amnesiac84** [BeWelcome/rox#224]
On signup page 1 (username, e-mail, etc) a new member has to chose their accommodation status. If someone oversees this and skips that last option, the error message is in black on the same line as the 2 houses. It can easily be overseen.
Maybe adding a red color to the text, box it or bring it to the top of the page would make it clear that the last step is not complete.

**Comment by thisismeonmounteverest** [comment]
@amnesiac84 Did you check on beta? I recently worked on that part because something was not translatable. I might have fixed that as well.

**Comment by gbenouville** [comment]
Now the display is clear (tested on laptop and app), I think the issue can be closed.

**Comment by crumbking** [comment]
Fixed with last release.
