### ISSUE TITLE
Small display issue on iphone/safari

### ISSUE THREAD

**Issue by gbenouville** [BeWelcome/rox#227]
We got this feedback from a user:
On iphone SE (second edition) safari browser, the menu at the bottom of the screen is cut off. On bewelcome.org. it’s that same menu that includes the “report a bug” link. Below report a bug it looks like there’s a copywrite date but that’s almost completely cut off by the bottom of the screen.

**Comment by crumbking** [comment]
I could reproduce it. Please test a fix on beta.

**Comment by thisismeonmounteverest** [comment]
Fix deployed and tested.
