### ISSUE TITLE
Super slow login/landing page

### ISSUE THREAD

**Issue by Railslide** [BeWelcome/rox#23]
Logging in and/or loading the landing page takes quite some time. Anything we can do about it?

**Comment by djwinter** [comment]
I can't replicate in my environment the slowness I see production (1.5 seconds vs. 7+ seconds.) Sometimes I get up to 40 seconds in production. Makes me wonder if the server is struggling with concurrency.

Just loading the dashboard home runs over 500 queries, most of which are for the word translations. Maybe that could be cached to files to reduce number of queries. But it's hard to know what will make the best improvement without knowing exactly why the live site is stalling.

**Comment by amnesiac84** [comment]
I have the impression that loading the thumbnail avatars causes slow loading times. At least my network performance analyses show that it sometimes takes 1,5 seconds to load 1 picture. Showing 10+ pictures (new members + messages) takes 15+ seconds.

**Comment by thisismeonmounteverest** [comment]
I once did a profile run with my local install and I had the impression that the main issue was that two queries really take a long time: Finding the next visitors to the area and the getting the messages (which most users never ever see anyway).

**Comment by simison** [comment]
@amnesiac84 nope, the delay is before TTFB:

![image](https://cloud.githubusercontent.com/assets/87168/14833065/1318c5ba-0c06-11e6-963a-d8c685840bc2.png)

I'm already used to just leave BW load on background tab since it most of the time takes 5-10sec, sometimes even longer.

**Comment by simison** [comment]
More observations here; https://www.bewelcome.org/forums/s17411-Slow_server_/

**Comment by thisismeonmounteverest** [comment]
New website is life and loading is normal.
