### ISSUE TITLE
building docker version on fresh arm64

### ISSUE THREAD

**Issue by bwmravec** [BeWelcome/rox#230]
Hi everyone, I'm trying to build the docker version of rox on fresh ubuntu 20.04/arm64 and getting errors during yarn installation from the latest bootstrap4 branch

[4/4] Building fresh packages...
error /srv/bewelcome/node_modules/fibers: Command failed.
Exit code: 127
Command: node build.js || nodejs build.js
Arguments: 
Directory: /srv/bewelcome/node_modules/fibers
Output:
node-gyp not found! Please ensure node-gyp is in your PATH--
Try running: `sudo npm install -g node-gyp`
spawn node-gyp ENOENT
/bin/sh: nodejs: not found

where would the best place in the setup to integrate the missing package?

**Comment by thisismeonmounteverest** [comment]
@bwmravec This is not related to a missing node-gyp it seems. I recently run to the docker setup and that worked without issue.

Searching the web I found a few hits for yarn and node-gyp. fibers might be included with the wrong version because of the arm64 platform.

**Comment by thisismeonmounteverest** [comment]
Just found this one: https://github.com/RocketChat/Docker.Official.Image/issues/48

**Comment by bwmravec** [comment]
I can't find where exactly is the nodejs version for docker compilation defined :/

**Comment by thisismeonmounteverest** [comment]
Unfortunately me neither. Maybe the guy who created the docker support can help.

@vincentchalamon Do you know how to resolve this?

**Comment by vincentchalamon** [comment]
Hi folks, I'm checking locally with the latest version of the bootstrap4 branch.

Did you check rebuilding the yarn.lock file? The node packages depends on the system, so if the yarn.lock file has been generated on another system, that could explain the error...

**Comment by vincentchalamon** [comment]
Successfully built the bootstrap4 branch locally. FYI, the node version is v12.21.0

**Comment by bwmravec** [comment]
It does build on amd64 without issues, but can't make it work on arm64. How can I refresh yarn.lock for my local system?

**Comment by vincentchalamon** [comment]
You could try locally: `yarn install`, it should install the node packages according to your system

**Comment by thisismeonmounteverest** [comment]
@bwmravec Did you get it working (on your M1 Mac I assume)?

**Comment by bwmravec** [comment]
@thisismeonmounteverest I didn't make the docker version work on rpi 4 arm64 due some docker bugs, but manual installation worked fine so I went with that.
