### ISSUE TITLE
Downloading data fails

### ISSUE THREAD

**Issue by simison** [BeWelcome/rox#240]
When attempting to download my data, it fails:

1. Enter your pass at https://bewelcome.org/mydata

    <img width="1285" alt="Screenshot 2021-05-09 at 21 19 16" src="https://user-images.githubusercontent.com/87168/117582764-43ca7e00-b10c-11eb-86f3-bc4c3a984ce1.png">

2. Greeted by error

    <img width="775" alt="Screenshot 2021-05-09 at 21 18 49" src="https://user-images.githubusercontent.com/87168/117582765-462cd800-b10c-11eb-89d2-5e7fd4d1792b.png">

**Comment by thisismeonmounteverest** [comment]
@simison There was a release last weekend that hopefully addressed this. Could you try again?

**Comment by Jeroentetje3** [comment]
@simison It seems to be working, could you verify?
