### ISSUE TITLE
docker windows install bewelcome first time 

### ISSUE THREAD

**Issue by gboniscontro** [BeWelcome/rox#249]
I try to follow every step of the documentation installation to install the rox in windows 10

clone the repository branch develop
I download docker windows.
try to use command make install get the error 
 MINGW64 /d/aauser/rox (develop)
$ make install
git rev-parse --short HEAD > VERSION
test -f docker-compose.override.yml || cp docker-compose.override.yml.dist docker-compose.override.yml
curl https://downloads.bewelcome.org/for_developers/rox_test_db/languages.sql.bz2 -o ./docker/db/languages.sql.bz2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
make: *** [Makefile:19: install] Error 60

I try using the following command 
$ docker-compose up
Starting rox_sphinx_1 ...
Starting rox_db_1     ...
Starting rox_mailer_1 ...
Starting rox_sphinx_1 ... done
Starting rox_mailer_1 ... done
Starting rox_db_1     ... done
Recreating rox_php_1  ...
Recreating rox_php_1  ... done
Recreating rox_web_1  ...
Recreating rox_web_1  ... done
Attaching to rox_sphinx_1, rox_mailer_1, rox_db_1, rox_php_1, rox_web_1
db_1      | 2021-06-26 15:07:50 140564767725568 [Note] mysqld (mysqld 10.1.41-MariaDB-1~bionic) starting as process 1 ...
db_1      | 2021-06-26 15:07:50 140564767725568 [Note] InnoDB: Using mutexes to ref count buffer pool pages
db_1      | 2021-06-26 15:07:50 140564767725568 [Note] InnoDB: The InnoDB memory heap is disabled
db_1      | 2021-06-26 15:07:50 140564767725568 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
db_1      | 2021-06-26 15:07:50 140564767725568 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for memory barrier
db_1      | 2021-06-26 15:07:50 140564767725568 [Note] InnoDB: Compressed tables use zlib 1.2.11
db_1      | 2021-06-26 15:07:50 140564767725568 [Note] InnoDB: Using Linux native AIO
db_1      | 2021-06-26 15:07:50 140564767725568 [Note] InnoDB: Using SSE crc32 instructions
db_1      | 2021-06-26 15:07:50 140564767725568 [Note] InnoDB: Initializing buffer pool, size = 256.0M
db_1      | 2021-06-26 15:07:50 140564767725568 [Note] InnoDB: Completed initialization of buffer pool
db_1      | 2021-06-26 15:07:50 140564767725568 [Note] InnoDB: Highest supported file format is Barracuda.
db_1      | 2021-06-26 15:07:50 140564767725568 [Note] InnoDB: 128 rollback segment(s) are active.
db_1      | 2021-06-26 15:07:50 140564767725568 [Note] InnoDB: Waiting for purge to start
db_1      | 2021-06-26 15:07:50 140564767725568 [Note] InnoDB:  Percona XtraDB (http://www.percona.com) 5.6.44-86.0 started; log sequence number 1616817
db_1      | 2021-06-26 15:07:50 140564767725568 [Note] Plugin 'FEEDBACK' is disabled.
db_1      | 2021-06-26 15:07:50 140563806418688 [Note] InnoDB: Dumping buffer pool(s) not yet started
db_1      | 2021-06-26 15:07:50 140564767725568 [Note] Server socket created on IP: '::'.
db_1      | 2021-06-26 15:07:50 140564767725568 [Warning] 'proxies_priv' entry '@% root@a76062662cc2' ignored in --skip-name-resolve mode.
db_1      | 2021-06-26 15:07:50 140564767725568 [Note] mysqld: ready for connections.
db_1      | Version: '10.1.41-MariaDB-1~bionic'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution
mailer_1  | Starting MailCatcher
php_1     | standard_init_linux.go:228: exec user process caused: no such file or directory
mailer_1  | ==> smtp://0.0.0.0:25
mailer_1  | /usr/lib/ruby/gems/2.5.0/gems/thin-1.5.1/lib/thin/server.rb:104: warning: constant ::Fixnum is deprecated
mailer_1  | ==> http://0.0.0.0:80/
sphinx_1  | *** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
sphinx_1  | *** Running /etc/rc.local...
sphinx_1  | *** Booting runit daemon...
sphinx_1  | *** Runit started as PID 11
rox_php_1 exited with code 1
web_1     | 2021/06/26 15:07:51 [emerg] 1#1: host not found in upstream "php" in /etc/nginx/conf.d/default.conf:11
web_1     | nginx: [emerg] host not found in upstream "php" in /etc/nginx/conf.d/default.conf:11
rox_web_1 exited with code 1

**Comment by thisismeonmounteverest** [comment]
@gboniscontro Unfortunately, the certificate for downloads.bewelcome.org expired so the first step to have up-to-date translations fails. I hope the sysadmins fix that soon.

Then I see you're on windows if I read the MINGW64 correctly, there are a few issue with docker on Windows that I never found out how to circumvent. One being that the Symfony form component is corrupted.

**Comment by thisismeonmounteverest** [comment]
@gboniscontro The download should work now. 

But when I tested yesterday I again ran into the form component problem. The only way around that that I found is to put the source code into the file system for your local Linux kernel.

Do you by any chance have a docker account with support?

**Comment by TheRojam** [comment]
In such case @thisismeonmounteverest ping me :)

**Comment by thisismeonmounteverest** [comment]
@TheRojam Ping :)

If I recall correctly I asked about the account as we would need to upload logs and stuff which needs that.

**Comment by TheRojam** [comment]
Just wanted to say, in case of such problems like certs on something, ping me here and may on the mattermost.
