### ISSUE TITLE
E-mail template - Reset password with variables instead of correct translation

### ISSUE THREAD

**Issue by veroandi** [BeWelcome/rox#253]
Hello ! 

I tried to login at BeWelcome today but having forgot my password, I clicked on reset password option and I successfully received a reset email and changed my password. 

But the e-mail title and greetings are not correctly displayed (at least in Portuguese) :

![reset](https://user-images.githubusercontent.com/25018964/129618701-4dea5d5c-9ad2-4749-862d-c242a942afaa.JPG)

Steps: 
1- https://www.bewelcome.org/resetpassword
2- Username: my email address
3- Email received

**Comment by crumbking** [comment]
Thanks for reporting. Should be fixed now.

The subject for the mail is now: "Reset your password for BeWelcome"
Soon the translators will take care of the Portuguese version.

Also the Portuguese greeting should work now:
male: Caro username,
female: Cara username,
other: Caro/a username,

**Comment by crumbking** [comment]
Close as fixed.
