### ISSUE TITLE
On the places page I'm getting a login link when I'm already logged in

### ISSUE THREAD

**Issue by rafalkrupinski** [BeWelcome/rox#255]
From editmyprofile page I went to my region and saw this:
<img width="967" alt="Screenshot 2021-09-20 at 13 03 32" src="https://user-images.githubusercontent.com/3732079/133992257-8bab2798-dc81-4f66-917e-0d4bc7f2f5a7.png">

under **Członkowie** (members) there is **zaloguj się** (login), and that's an invalid link too

**Comment by thisismeonmounteverest** [comment]
I found the issue. The problem was in the way the queries where setup. You can check on https://beta.bewelcome.org
