### ISSUE TITLE
Feedback with no reply needed box

### ISSUE THREAD

**Issue by bwmravec** [BeWelcome/rox#256]
It seems that feedback form is not adding text with "no reply needed" to the email once the user check the box for not requesting the answer for its feedback. Tested on beta.

**Comment by thisismeonmounteverest** [comment]
@bwmravec I can't reproduce with the code locally. Do you recall which category you choose?

Was it with a logged in user or not logged in?

**Comment by bwmravec** [comment]
I tested on beta as logged user, it seems to be the same for all categories. I tested all of them. When "no reply needed" checkbox is checked, this info is never sent

**Comment by thisismeonmounteverest** [comment]
Thanks for reporting code is much cleaner now :)
