### ISSUE TITLE
Suspending old accounts

### ISSUE THREAD

**Issue by ghost** [BeWelcome/rox#262]
I guess another newsletter will be sent after this year's GA, so it would be nice if someone could take care of implementing [last year's GA decision](https://www.bevolunteer.org/wp-content/uploads/2021/01/GA_28-29.11.2020_minutes.pdf) (see point 15) and make a script to automatically suspend members who have been inactive for more than 5 years. It would save us a lot of work in Support team: we receive about 1500 bounces after each newsletter, and most of them are old inactive accounts that we have to suspend manually.

**Comment by gabriel-BW** [comment]
This one can be closed, cleanup of old accounts was done...

**Comment by crumbking** [comment]
Close as suggested
