### ISSUE TITLE
Design issue - Button to delete a language

### ISSUE THREAD

**Issue by ghost** [BeWelcome/rox#266]
We had this feedback from a user, which I tested and confirmed: on the "Edit profile" page, "languages" tab, the button to delete a language only works when you click on the outer part. Clicking the inner red circle (X) produces no result.
![image](https://user-images.githubusercontent.com/78049499/143679104-be491c37-2b1b-49ff-af8d-f1886b43501b.png)

**Comment by gabriel-BW** [comment]
Tested on Chrome, laptop and mobile, and it works.

**Comment by arunanm** [comment]
Verified on Vivaldi 5.2.2623.46 (Stable channel) (64-bit), Chromium based browser and it works!

**Comment by crumbking** [comment]
Close as fixed on beta and live.
