### ISSUE TITLE
Sent request view shows place and language of sender

### ISSUE THREAD

**Issue by crumbking** [BeWelcome/rox#269]
![Screenshot_20220106-152510](https://user-images.githubusercontent.com/1238326/148397806-57c0d9bc-859d-4ab4-86d1-2e6d701c99bd.png)

**Comment by crumbking** [comment]
Should be fixed with:
https://github.com/BeWelcome/rox/commit/952013ad261a24607f5e9cf5a9bcdcaede02b660
Let's see on beta

**Comment by gabriel-BW** [comment]
Seems to work (tested on chrome, laptop and mobile):
![BW](https://user-images.githubusercontent.com/96146559/149012596-4cabb454-45c1-4ed8-bbac-9bb8e2458d33.jpg)
