### ISSUE TITLE
Simplify the conversation user interface

### ISSUE THREAD

**Issue by tempral** [BeWelcome/rox#279]
Now messages between two persons are full of nested replies, with many copies of the same messages!!

Display everything like a chat can be much readable

**Comment by gabriel-BW** [comment]
BW forum discussion: https://www.bewelcome.org/group/571/forum/s24392-Simplify_the_conversation_user_interface_
This is only likely to happen for old messages.

**Comment by thisismeonmounteverest** [comment]
Closing as conversation code was completely rewritten.
