### ISSUE TITLE
Change the default post/thread visibility

### ISSUE THREAD

**Issue by gabriel-BW** [BeWelcome/rox#280]
Following a discussion [here](https://www.bewelcome.org/forums/s24385/#post123929) (BV group), and I believe several ones before, can we change the default setting for the visibility of new threads and posts in public groups? Make them visible for all members instead of group members only. That can probably be done quickly, unlike the global redesign of groups which would be needed to fully address the issue.

**Comment by crumbking** [comment]
Close as tested and fixed on beta and live.
