### ISSUE TITLE
Don't send email notifications for comments you have posted yourself in BW forum threads

### ISSUE THREAD

**Issue by nekohayo** [BeWelcome/rox#286]
When I'm commenting in a forum thread (or activity, or private message), there is no reason to send me an email notification showing me the comment I just posted. I know what I wrote, and this just creates noise compared to real notifications (i.e. other people replying in the thread).

**Comment by thisismeonmounteverest** [comment]
This is by intention. Also see #288 if your own posts are missing threading doesn't really make sense.

**Comment by nekohayo** [comment]
OK, so if it is intentional, the question becomes: why? When is it relevant for me to be notified that I just replied to something on the site?

Threading without my own comments totally works in practice. That's exactly how GitHub, GitLab, Discourse, and other web-based communication systems (including all social media websites) work. They don't spam me with a superflous notification when I write a comment directly via the web interface (nor when I would reply via email, for that matter, but then in that case it doesn't matter).

**Comment by thisismeonmounteverest** [comment]
Posting to an mailing list will always send you a copy of your message.  That social media is a step backwards in usability is nothing new.

Anyway if you enable notifications and want them nicely threaded I expect you want to have an archive of the conversations. Leaving your own voice out of that will render that useless, as you will always have to go back to the website to see your own posts.
