### ISSUE TITLE
Website URL in profile gets converted from HTTPS to HTTP

### ISSUE THREAD

**Issue by nekohayo** [BeWelcome/rox#290]
If you set a URL with HTTPS (or no protocol) in the "Website" field in your profile (or presumably anywhere in your profile?), bewelcome downgrades that URL's protocol to `http://`, which is not the right thing to do nowadays, especially as 90%+ of websites (and browsers) have moved on to enforced HTTPS.

**Comment by thisismeonmounteverest** [comment]
Should be fixed already.

**Comment by crumbking** [comment]
Close as fixed on beta and live.
