### ISSUE TITLE
Username header at the top of the profile is not hyperlinked to the profile's home page

### ISSUE THREAD

**Issue by nekohayo** [BeWelcome/rox#291]
It is a common pattern in most/all social web platforms that you can click your own username to go visit your profile's main page. However, in BW, this is not the case, and there are no links in the sidebar to go back to the "home" page of my profile. So please hyperlink the text portion of the `h2` containing the username at the top of a user's profile, especially when not on the profile's home page.

**Comment by thisismeonmounteverest** [comment]
There is a link to your profile in the member menu. Isn't that enough?

**Comment by nekohayo** [comment]
Unfortunately I never intuitively think of using the global navbar's submenus for that when I'm already on the profile page that has a sidebar contextual menu. I would expect either the username to be clickable like elsewhere, and/or to have a "Profile home" menu item in the sidebar.

**Comment by thisismeonmounteverest** [comment]
Actually after checking the code and site again, the avatar image is linking back to the main profile page.

**Comment by nekohayo** [comment]
Hmm that's weird, because when I click on my photo at the top of the sidebar (as I thought of that as well) it only expands the size of the photo rather than linking to the profile homepage...
