### ISSUE TITLE
Documentation not accessible

### ISSUE THREAD

**Issue by tillwenke** [BeWelcome/rox#296]
"Doc tree" https://github.com/BeWelcome/rox/blob/develop/doc/book returns 404. And (thus?) compiling with mkdocs also does not work (under Ubuntu 22).
~ to be found in README

**Comment by thisismeonmounteverest** [comment]
@TillWenke Yes, that is unfortunately true. I removed the files 5 years ago when the project was migrated to full symfony and not a weird mix of laravel and symfony.

I try to bring some documentation back. Probably needed to start working on the right stuff.

**Comment by TillWenke** [comment]
Hi, could you provide a hotfix (google drive whatever) - without doc it seem hard to start :)

**Comment by thisismeonmounteverest** [comment]
The last commit readded the missing files and you can generate docs again. But the files are outdated, so another update will be needed to get you started.

For starters:

- Code is based on Symfony with Doctrine and is organized accordingly.
- There is a lot of old code that still needs to be migrated below the build.
- Docker setup should get you started with a test environment quickly.

**Comment by TillWenke** [comment]
appreciate it

**Comment by thisismeonmounteverest** [comment]
Updated some more. Please let me know if you need more information.
