### ISSUE TITLE
Server error when trying to join a group in Beta Version

### ISSUE THREAD

**Issue by maninthemiddle01** [BeWelcome/rox#308]
expected behaviour:
- Join a group (which works in normal mode of BeWelcome-Website)

Behavior of the beta.bewelcome.org:
Find a group you want to join
→ click join group
→ select e-mail notification (yes|no doesn't matter)

You'll end up with: "Server error"

Firefox 102.4.0esr (64-Bit)

**Comment by thisismeonmounteverest** [comment]
@maninthemiddle01 I have a look what's going wrong. Thanks for reporting.
