### ISSUE TITLE
Filter users by group membership

### ISSUE THREAD

**Issue by arielpontes** [BeWelcome/rox#323]
When searching for users in a certain city, it should be possible to filter the resulting users by group membership. This way I could for example look only for Berlin users who are in the group "Atheists & Agnostics". I'm not a PHP developer, but I am a developer (Python/Django) so I could help implement this if anybody is willing to work with me.

# Motivation
I'm an active member of two international communities: secular humanism and effective altruism. As a volunteer for local organizations, I've done quite a bit of community building work in the past few years. One common need that people have in these communities is a tool for finding hosts when they travel. This is good for networking and creating a strong sense of community. The EA community has even implemented a [solution](https://coda.io/d/EA-Houses_dePaxf_RJiq/EA-Houses-couchsurfing-renting-to-give_suGq6) by this using coda.io. Recently I mentioned this at a secular humanist conference and many people were interested in doing something similar for the humanist community. I think many different communities would benefit for having an internal couchsurfing-style platform, but at the same time it seems inefficient to create a separate one for each community.

I think a much easier and cleaner solution to this problem would be to implement filtering by group. This way I could simply create a "Secular Humanism" group and promote it in secular humanist circles, and promote the "Effective Altruism" group in EA circles. If I joined any other community, I could do the same for that. I think this could actually help BeWelcome grow, since it could potentially be adopted by various communities.

**Comment by thisismeonmounteverest** [comment]
@arielpontes You can filter by groups that you are a member of. Just make sure to show the search options to be able to see the groups filter.
