### ISSUE TITLE
Signup broken with csrf error in japan

### ISSUE THREAD

**Issue by ysangkok** [BeWelcome/rox#324]
I am in japan and signup isn't working. I get an error about csrf expiry whe clicking the link in the email verification. I searched for a test related to timezones and csrf but i didnt find it. Would be nice to have this test to rule out that the time zone is the problem. Thanks.

**Comment by ysangkok** [comment]
Okay the csrf failure is on login. On email link clicking, this is the failure : ![Uploading Screenshot_20230831_214049_com.huawei.android.launcher.jpg…]()

**Comment by ysangkok** [comment]
![Screenshot_20230831_214049_com huawei android launcher](https://github.com/BeWelcome/rox/assets/284023/9208ffbf-8671-4618-91bd-30a0960fd0b0)

**Comment by ysangkok** [comment]
![Screenshot_20230831_214615_com android chrome](https://github.com/BeWelcome/rox/assets/284023/dc8ffa2e-7f93-4602-aef7-fdb9d9c43a71)

**Comment by thisismeonmounteverest** [comment]
@ysangkok The CRSF token is checked on the server side so I'd expect that the timezone doesn't make any difference.

The 'Provided key isn't correct' message is shown when you try to confirm your email address but you're already registered or the link is corrupted.

Could you show the message, when you access https://www.bewelcome.org and enter your username and password there?

**Comment by ysangkok** [comment]
I am not able to reproduce this, I suppose it must have been fixed, maybe in my machine configuration.
