### ISSUE TITLE
Cannot paste text in editor field when requesting as a guest

### ISSUE THREAD

**Issue by bitstarr** [BeWelcome/rox#325]
When using Firefox (Version 117, my main browser), I can't paste text into the editor field (https://www.bewelcome.org/new/request/USERNAME)

I tried Chrome to compare and there it works. I don't want to be forced to use Chrome.

**Comment by thisismeonmounteverest** [comment]
@bitstarr Which platform? On Windows that works fine as far as I checked. 

If mobile (Android) could you check if it works on https://beta.bewelcome.org where the CKEditor is a newer version?

**Comment by bitstarr** [comment]
It's on Windows. Not sure what the issue exactly is, because the FF dev edition does not show this behaviour. I tried disabling all extensions in my main Firefox, but nothing changed. Maybe a locally isolated problem.

**Comment by thisismeonmounteverest** [comment]
@bitstarr You could still check on beta on Windows if that changes anything.

**Comment by bitstarr** [comment]
Same outcome still
