### ISSUE TITLE
Broken hyperlinks in Polish 

### ISSUE THREAD

**Issue by millamy** [BeWelcome/rox#327]
There is a problem with anchored links in Polish page translation.
Steps to reproduce: 
1. Navigate to [Volunteering]
2. Change page translation to Polish
3. See sections Testing and Design (Testowanie and Projektowanie in Polish)
![image](https://github.com/BeWelcome/rox/assets/92036863/a3f4ae0b-9b18-45d0-9d25-1e5a7256d956)
![image](https://github.com/BeWelcome/rox/assets/92036863/aecede0a-bcc8-44d1-ad5b-b01180ead708)

**Comment by thisismeonmounteverest** [comment]
@millamy Thanks I fixed the translations that caused that.
