### ISSUE TITLE
Duplicate cities 

### ISSUE THREAD

**Issue by millamy** [BeWelcome/rox#328]
There is a problem while browsing by city, duplicate Kraków occurs.
Steps to replicate:
1. Navigate to Find members -> Browse countries
2. Choose Poland ->Lesser Poland
3. You will see two Krakóws if browsing in Polish, or Kraków and Krakow when browsing in English
![image](https://github.com/BeWelcome/rox/assets/92036863/58baa252-a529-4cff-912a-efca4eb3e10b)

**Comment by thisismeonmounteverest** [comment]
@millamy Thanks for reporting, fixed.
