### ISSUE TITLE
Logged in user is asked to log in

### ISSUE THREAD

**Issue by millamy** [BeWelcome/rox#329]
When browsing cities, clicking on one of the duplicate Krakóws (the one with 2 users), logged in user is asked to log in again.
Steps to reproduce:
1. Navigate to Find members -> Browse countries
2. Choose Poland ->Lesser Poland
3. You will see two Krakóws if browsing in Polish, or Kraków and Krakow when browsing in English.
4. Click on the one with 2 users
![image](https://github.com/BeWelcome/rox/assets/92036863/d2d3f0ed-0f77-46a8-ba16-98e952466eaf)

**Comment by thisismeonmounteverest** [comment]
@millamy Fixed, thanks for reporting.
