### ISSUE TITLE
E-mail not showing correctly

### ISSUE THREAD

**Issue by millamy** [BeWelcome/rox#334]
Steps to reproduce:
1.  Go to [Safety] -> [Safety Information]
2. See "Contact the Safety Team" 
3. E-mail address is visible as  safety [at] bewelcome [dot] org

![image](https://github.com/BeWelcome/rox/assets/92036863/8b5475de-82c3-4221-9f66-9545aa22e7e7)

**Comment by thisismeonmounteverest** [comment]
@millamy That is intentional, as the safety pages are accessible without login they can be scraped which means that there might be a lot of unwanted contacts to the safetyteam.
