### ISSUE TITLE
Unclear instructions on gallery management

### ISSUE THREAD

**Issue by o1la** [BeWelcome/rox#335]
When clicking Move images or Delete images without selecting any image, page not found occurs. We suggest adding pop up information with instructions. 

Steps to reproduce:
1. Go to [Profile] -> [Gallery]
2. Without clicking anything else click [Move images] or [Delete images] or press enter when cursor inside [Create new album] (without selecting the point next to the text field)

User is redirected to https://www.bewelcome.org//

<img width="1678" alt="Zrzut ekranu 2023-11-24 o 10 33 44" src="https://github.com/BeWelcome/rox/assets/91129287/f39681a0-a5f8-4990-8c25-3dc690509b6d">

**Comment by thisismeonmounteverest** [comment]
@o1la Thanks for reporting.

The gallery pages seem to lack some checks if the entered data is valid (or that check fails).
