### ISSUE TITLE
Incorrect Information and Formatting on Gallery - Upload Image page

### ISSUE THREAD

**Issue by ikolton** [BeWelcome/rox#336]
### Steps to Reproduce
1. Visit as a logged user the following URL: [https://www.bewelcome.org/gallery/upload_multiple](https://www.bewelcome.org/gallery/upload_multiple)
2. Observe the text over the fields for uploading images.

### Current Behavior
The text displayed over the image upload fields is as follows:

> **Gallery -
> Upload Image**
> Here you can upload images into your gallery. You may select several images at once. The maximum size for images is 2MB, and the maximum number of pixels (width x height) is {pixels}.

### Expected Behaviour
- The maximum size for images should be 8MB. ([According to Second Release 2023 community news](https://www.bewelcome.org/communitynews/220))
- `{pixels}` should display an actual maximum number of pixels (width x height).

## Environment
- Browser: Microsoft Edge
- Operating System: Windows 11

## Screenshots
![image](https://github.com/BeWelcome/rox/assets/96392714/f4cd9e1b-7b31-41da-8858-08faa0d484bc)

**Comment by thisismeonmounteverest** [comment]
@ignajlo Interesting. The first one seems to be a configuration issue of the webserver (as you can see on beta, where the amount is correctly shown as 8MB). The pixels part got removed from the (English) translation now on both www and beta.

Thanks for reporting.

**Comment by thisismeonmounteverest** [comment]
Fixed the server config.
