### ISSUE TITLE
Picture not visble in a mail with stay request notification

### ISSUE THREAD

**Issue by millamy** [BeWelcome/rox#343]
Attached picture in the stay request comment field is not visible in the mail notification.
On the web page, the picture is displayed correctly.

Steps to reproduce:
1. Have access to two accounts.
2. Create a stay request from one account, add a picture to the message and check the email notification.
![image](https://github.com/BeWelcome/rox/assets/92036863/4f2cf800-6d8e-4efa-b562-d018489e42d2)

**Comment by thisismeonmounteverest** [comment]
That's a design decision not to add images as attachments to the notifications. It is expected that the members login anyway to reply to the request.
