### ISSUE TITLE
Unclear drop down menu formatting when creating trip 

### ISSUE THREAD

**Issue by o1la** [BeWelcome/rox#345]
When creating trip using full screen drop down arrays are overlapping text (number of travellers, invitation radius >= 100km).

<img width="1669" alt="image" src="https://github.com/BeWelcome/rox/assets/91129287/8bd63d82-8a18-48a0-b4f4-29e2ecbed15d">

**Comment by thisismeonmounteverest** [comment]
Fixed with commit https://github.com/BeWelcome/rox/commit/3e30db15f8bf6d1db3df95881a51a3a9fd36f63d.
