### ISSUE TITLE
Trips not showing when any trip date is above 2 week mark

### ISSUE THREAD

**Issue by o1la** [BeWelcome/rox#346]
Trip not visible when start or end date is above 2 weeks mark from today.
See example below:

![387483024_244096755369674_5769162920661521403_n](https://github.com/BeWelcome/rox/assets/91129287/66827336-e9a9-46e0-8408-995172177875)

<img width="1663" alt="Zrzut ekranu 2023-12-15 o 09 34 45" src="https://github.com/BeWelcome/rox/assets/91129287/60661ed1-f370-4476-af48-a48f06358600">

When date is below 2 weeks mark trip is showing correctly:
<img width="1666" alt="Zrzut ekranu 2023-12-15 o 09 35 30" src="https://github.com/BeWelcome/rox/assets/91129287/121ad8fa-a18c-427f-bef9-a56cf0a9b9de">

Checked on beta and www.

**Comment by o1la** [comment]
And what does leg mean? '1 Legs' seems incorrect and confusing. :(

**Comment by thisismeonmounteverest** [comment]
Leg is a normal turn for journeys. Search for flight leg as an example, so that will stay. But 1 legs is still wrong.

Trips that are longer than 2 weeks in one place are filling up the small number of places we have in the visitors tab so they are filtered out. But should be shown here.

**Comment by thisismeonmounteverest** [comment]
Should be fixed now (removed the restriction for two weeks trips).
