### ISSUE TITLE
Signup fails on step 3 Location

### ISSUE THREAD

**Issue by PaulVe2024** [BeWelcome/rox#351]
Signup fails on step 3 Location https://www.bewelcome.org/signup/3
Pressing "next step" button reloads page without any errors

<img width="2556" alt="Screenshot 2024-02-02 at 01 17 04" src="https://github.com/BeWelcome/rox/assets/158529652/6b42cfe5-8068-4e64-b32b-1be892e00cd2">

Related error is when trying to entering city, there is error for network fetch for every letter entered in "Set your hosting location" field.

<img width="2556" alt="Screenshot 2024-02-02 at 01 26 02" src="https://github.com/BeWelcome/rox/assets/158529652/e7c67681-d1a1-45f6-a2e7-99cf43c0b0c6">

**Comment by thisismeonmounteverest** [comment]
@PaulVe2024 Unfortunately, the server responds here with a 500 error and the search box doesn't communicate that. Issue should be solved on server side now, hence closing the ticket.
