### ISSUE TITLE
How can I contribute?

### ISSUE THREAD

**Issue by smoqadam** [BeWelcome/rox#36]
Hi guys
I've been working in PHP about 6 years and now I want to contribute some open-source projects. I think BeWelcome is a good starting point, because it has a lot of potential to be a first host-guest website in the world.
I was looking for `CONTRIBUTING.md` file but I couldn't find it. Now I want to know how can I contribute and what is the starting point?
thanks

**Comment by thisismeonmounteverest** [comment]
Send a private message.
