### ISSUE TITLE
Discrepancy between displayed comments

### ISSUE THREAD

**Issue by amnesiac84** [BeWelcome/rox#39]
At this moment, the map search gives only the number of comments left on a profile page of active members. It ignores comments from inactive members.

For example:
a member has 18 profile comments, and 8 of the authors are inactive. The map search states that the member has 10 profile comments. The text search states 18 comments. On the profile page 18 comments can be read.

**Comment by thisismeonmounteverest** [comment]
Closed as the new site uses the same method to count the comments everywhere.
