### ISSUE TITLE
Member's forum posts page doesn't show group for each post

### ISSUE THREAD

**Issue by jhodgdon-drp** [BeWelcome/rox#54]
Go to your profile. Click on "Forum posts", which takes you to a page like
https://www.bewelcome.org/forums/member/[your member name]

On this page, you can see the posts that you have made. Unfortunately, you cannot tell which group the posts were made in, just the thread/topic title, which (out of context) could be fairly confusing.

**Comment by thisismeonmounteverest** [comment]
This has been fixed a while ago but was never closed.
