### ISSUE TITLE
Messaging: make it possible to reply to last sent message

### ISSUE THREAD

**Issue by axelsimon** [BeWelcome/rox#56]
Hi and thanks for making rox (and BeWelcome)!
Here's the issue:
You send a message to someone. A few days later, you realise they haven't replied and so you want to send them a second message. There is currently no _easy_¹ way to send a second message that is connected to the first one (ie: keeps the conversation context).

Most email clients make it possible to reply to your own sent messages, as if they had been received. This will automatically quote your own message, and let you write your new message above.

A simple "reply" button under messages, next to "edit" (which I'm not sure should exist, by the way), would be a simple way of sending follow ups while maintaining the conversation context.

Thanks!

1. Sure, you can copy your last sent message, click "reply" to your correspondent's last message, paste your last sent message, select the whole text in the text box, click "blockquote" and then start typing above that, but only nerds like me will do that.

**Comment by thisismeonmounteverest** [comment]
Should be fixed with the last deploy on alpha.bewelcome.org.

**Comment by amnesiac84** [comment]
Seems to work with the new messaging layout
