### ISSUE TITLE
Impossible de se connecter / problème avec l'envoi de nouveau mot de passe / réponse du support nulle

### ISSUE THREAD

**Issue by wrols** [BeWelcome/rox#58]
Bonjour,
J'ouvre une demande de problème sur github car le boggue perdure depuis trop longtemps maintenant. Depuis plusieurs mois, il m'est impossible de me connecter sur le site bewelcome.org.
J'ai donc fait la demande pour recevoir un nouveau mot de passe. Je reçois bien les courriels avec le nouveau mot de passe. Mais impossible de me connecter avec mon identifiant habituel et le nouveau mot de passe... ??
J'ai donc à 2 reprises envoyer un rapport de bug via le site bewelcome.org mais aucune réponse depuis bien plus d'un mois déjà.
Le projet est-il encore vivant ou est-il juste mort ? Il ne serait probablement pas encore mort vu qu'il y a eu un commit il y a moins d'un mois.
Cordialement.

**Comment by amnesiac84** [comment]
Should be fixed now
