### ISSUE TITLE
Sign in with both username as e-mail address

### ISSUE THREAD

**Issue by amnesiac84** [BeWelcome/rox#59]
Since more and more websites let you login with an e-mail address, the members assume it can be done on BeWelcome as well. This saves frustration with members and work for the support team.

**Comment by thisismeonmounteverest** [comment]
To achieve this we need to move the email address from the cryptedfields table to a new table which should contain all member attributes like name etc. in the long run.

**Comment by amnesiac84** [comment]
Looking good!
