### ISSUE TITLE
Easy way to link to geographical landing page

### ISSUE THREAD

**Issue by guaka** [BeWelcome/rox#6]
I'd like to link to BeWelcome from http://nomadwiki.org, ideally automatically from all city and country pages. For this to work there should be something like bewelcome.org/geo/Paris and bewelcome.org/geo/France - these 301 pages can be redirected elsewhere of course, but I don't want to manually construct this link for each page.

See also https://github.com/warmshowers/Warmshowers.org/issues/620

**Comment by thisismeonmounteverest** [comment]
Links to places are constructed in an easy and reproducible way removing ambiguity:
/countryname/2 letter countrycode/name of region/admin id from geonames/name of place/geoname id

The suggested redirects don't make sense to me as it is unclear why /geo/Paris should be the capital of France and not little Paris in Texas.

Closing as won't fix.

**Comment by simison** [comment]
Man... lemme put it this way;

we have 3 major underground travel wikis with some 150K unique visitors a month and some 7K pages in over 10 languages. All we have is a name of the article (like "France" or "Paris") and we'd like to have an easy way to link to BeWelcome.

**Comment by thisismeonmounteverest** [comment]
How do you map the names you have to the real place?

**Comment by simison** [comment]
Namespace is built manually, just like at Wikipedia (we use the same software); https://en.wikipedia.org/wiki/Paris

Ideally it would be a search that results to most likely place (totally to Paris in France instead of Texas...). Example: https://www.trustroots.org/#!/search?location=Paris,France
