### ISSUE TITLE
Geonames Attribution Missing

### ISSUE THREAD

**Issue by plambros** [BeWelcome/rox#60]
As per the title, our geodata provider (geonames.org) license their work under a Creative Commons Attribution 3.0 License, but none such attribution can be found in the repo or the site. Can we amend this?

**Comment by thisismeonmounteverest** [comment]
Added a credits page to the new code as we need to attribute more than just Geonames.

**Comment by thisismeonmounteverest** [comment]
Added OpenStreetMap to the credits page.
