### ISSUE TITLE
Password reset doesn't work in all cases

### ISSUE THREAD

**Issue by amnesiac84** [BeWelcome/rox#61]
This should be revalued / rewritten, or give the Support Team the option to manually set a new temporary password.

**Comment by thisismeonmounteverest** [comment]
This issue is fixed on production now.

Need a better solution for the new website. Adding milestone and recode label accordingly.

**Comment by amnesiac84** [comment]
Seen the lack of new tickets lately, I assume this issue has been solved. Unless someone comments soon, I will close this issue

**Comment by thisismeonmounteverest** [comment]
Password reset was complete rewritten due to security concerns. Closing as fixed.
