### ISSUE TITLE
Allow only following specific threads

### ISSUE THREAD

**Issue by jidanni** [BeWelcome/rox#65]
1. User visits http://www.bewelcome.org/groups/570/membersettings
2. User sees ```I want to receive e-mail updates from this group: ￼ No ￼ Yes```
1. If 'no' User expects to also see a setting to still receive e-mail updates from:

> 1. Threads he has started
> 1. Thread he has comment on
> 1. Threads he has marked as following

Yes, only following specific threads is probably already implemented. It's just that the user visiting the above URL can't tell.

**Comment by thisismeonmounteverest** [comment]
@jidanni: Sorry for this really late reply.

For threads you want to follow you the 'Subscribe' button.
