### ISSUE TITLE
No need to send the user a copy of the message he posts to groups

### ISSUE THREAD

**Issue by jidanni** [BeWelcome/rox#66]
There is no need to send the user an e-mail copy of the message he posts to groups.
Just like GitHub does not send one a copy of the issues we post here.

**Comment by amnesiac84** [comment]
I disagree, the e-mails can be used to archive discussions. To get the full history of the group discussion, the own entries should be sent as well.
One could find back a post he wrote or find the original text he wrote before editing it.

Maybe an opt-out or opt-in would be an option.

**Comment by jidanni** [comment]
All I know is one of your members came here and took a warm shower,
complimenting me that it was great, then told staff that I had no shower
facilities, so my account got closed. So I can't help with any more
bugs. Sorry.

**Comment by amnesiac84** [comment]
Off topic: I just checked and your account is active... No one gets banned or suspended for a complaint of not having shower facilities

**Comment by jidanni** [comment]
(Oops I, confused WarmShowers and BeWelcome. Sorry.)

**Comment by jidanni** [comment]
Mailman has this option:
https://www.gnu.org/software/mailman/mailman-member/node23.html

**Comment by thisismeonmounteverest** [comment]
We already have a lot of options (preferences) adding more should be avoided if not essential for running the site in a meaningful way. Therefore closing and adding wontfix label.
