### ISSUE TITLE
Not possible to paste a text from mobile

### ISSUE THREAD

**Issue by Anatolt** [BeWelcome/rox#67]
It's not possible to paste a text in private message. 
It says "use Ctrl+v"
Android

**Comment by thisismeonmounteverest** [comment]
This is due to the used (rather old) version of TinyMCE. 

There seems to be an experimental version with mobile support. I try to get that onto beta.

**Comment by thisismeonmounteverest** [comment]
I updated TinyMCE to the latest version. Could you please test if that works for you?

(Check https://beta.bewelcome.org and use the same credentials as usual.)

**Comment by thisismeonmounteverest** [comment]
Updated production.
