### ISSUE TITLE
Add third-party application restrictions to github organization

### ISSUE THREAD

**Issue by Railslide** [BeWelcome/rox#68]
Not really a rox-related bug, but would it be possible to enable third-party application restrictions for BW organization on github?

'Cause I'm trying to set up CI at work and it looks like BW allows third-party access by default (i.e. any member with read access can authorize an application to access BW organization's data) and I'd rather not give access for BW if possible (I don't think we have particularly sensitive data in BW github organization, but still)

A good read about third party restrictions can be find [here](http://crimsonfu.github.io/2015/02/22/owners-of-organizations-on-github-should-carefully-set-up-third-party-application-restrictions.html)

**Comment by thisismeonmounteverest** [comment]
Enabled 3rd party restrictions. Thanks for the pointer.
