### ISSUE TITLE
Split requests and messages?

### ISSUE THREAD

**Issue by thisismeonmounteverest** [BeWelcome/rox#69]
Requests could/should be sorted by date of request not date of sending.

Code gets a bit confusing with the mix of requests and messages.

**Comment by thisismeonmounteverest** [comment]
Add an icon for requests with its own overlay for unread to the menu bar?

**Comment by amnesiac84** [comment]
Added an icon, does not count the requests yet, only the unread messages.

**Comment by amnesiac84** [comment]
This has been done, if I'm not mistaken
