### ISSUE TITLE
Privacy settings for blogs do not work correctly

### ISSUE THREAD

**Issue by tanerkuc** [BeWelcome/rox#7]
Trac issue #1976 reported by sitatara:

> When I create a blog post and set it to "private" everyone who knows the direct link, can access the blog post. So, basically it currently is the same as the setting "protected".
> By the way, I don't quite understand why we do not offer a "members only" visibilty setting for blog posts.

**Comment by tanerkuc** [comment]
I'm working on this, I currently don't have permission to assign this to myself though.

**Comment by thisismeonmounteverest** [comment]
Please don't as it is planned to drop the feature entirely.
