### ISSUE TITLE
#Signup

### ISSUE THREAD

**Issue by thisismeonmounteverest** [BeWelcome/rox#71]
- can't get past step 4 - showing input array (with password as cleartext)
- Language selector not showing/working properly

**Comment by thisismeonmounteverest** [comment]
Likely an issue with a non existing mailserver. Could you please check if it works on alpha?

**Comment by amnesiac84** [comment]
Issue is also present on alpha

Besides that (maybe another bug): there's no check if the password or the e-mail address is the same and some fields can be blank, even though they shouldn't.

**Comment by amnesiac84** [comment]
Let me know when I can test this on alpha. Not able to access signup locally
