### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by thisismeonmounteverest** [BeWelcome/rox#73]
Add a possibility to translate on the new website as the old version doesn't work anymore.

**Comment by amnesiac84** [comment]
I changed the website to Dutch, then saw that there's a 100% fall-back on English. When I opened the wordcode in Dutch there was a suitable translation though. Editing or updating didn't change the behaviour, the wordcodes remained in English.

**Comment by thisismeonmounteverest** [comment]
Need to update the allowed languages. Symfony currently allows to load the translations from the database but enables locales based on a file in the file system. Weird stuff.

**Comment by amnesiac84** [comment]
Is this issue solved? I guess translation on the new website is possible, right?

**Comment by thisismeonmounteverest** [comment]
Been there done that. Closing.
