### ISSUE TITLE
[Dashboard] Searching destination does not redirect to the place in map search

### ISSUE THREAD

**Issue by amnesiac84** [BeWelcome/rox#78]
When entering a destination on the Dashboard page (Where do you want to go?) it redirects to an empty map.

**Comment by amnesiac84** [comment]
Redirects to the dashboard page

**Comment by thisismeonmounteverest** [comment]
Tested this while fixing #104. Didn't see any issue.

Please check and close.

**Comment by amnesiac84** [comment]
It now leads to the 'search by username' page
