### ISSUE TITLE
Certain loactions does not show up in text search

### ISSUE THREAD

**Issue by Railslide** [BeWelcome/rox#8]
To reproduce: search for Crete in text search --> nothing related to Greece comes up

Works as intended in map search.

Locations affected (spotted so far):
- Crete
- Transnistria

**Comment by thisismeonmounteverest** [comment]
Crete and Transnistria aren't locations but regions. Regions aren't supported in the text search yet.

As a first step the resulting page should be fixed as the footer is misaligned and the message is obviously wrong as it doesn't show anything.

Second regions shall finally be supported.

**Comment by Railslide** [comment]
Can we add a warning somewhere? Like in the text under text search or in the result page? So that members don't contact us thinking that it is a bug

**Comment by PLP-GTR** [comment]
I think this is already fixed. If I enter "Kreta" (Crete) the list also shows Administrative Units:

![image](https://github.com/BeWelcome/rox/assets/3023230/e544c969-8b95-4a0b-9c81-cdb06dbf0d44)

The results look fine, too:
![image](https://github.com/BeWelcome/rox/assets/3023230/5520385d-8a42-4bee-8fae-283b546b1c70)


Same with Transnistria:

![image](https://github.com/BeWelcome/rox/assets/3023230/97d2e03d-c4ef-459d-b6a5-e4da2a2270e6)

@thisismeonmounteverest can you confirm & eventually close the issue?

**Comment by thisismeonmounteverest** [comment]
@PLP-GTR Thanks for checkin these old issues. Definitely fixed.
