### ISSUE TITLE
Language selection

### ISSUE THREAD

**Issue by crash-g** [BeWelcome/rox#88]
- Top-right language selector button in home page does nothing when clicked.
- Bottom language selector button will always show English as the current language, even after a new language has been selected (and the rest of the UI is updated). As a result, it is not possible to go back to English, but it is possible to select other languages.

Browser: Firefox 63.0.3
OS: Mint 18.3

**Comment by thisismeonmounteverest** [comment]
Fixed by changing the language selector from a drop down to a select2 language select as in the footer. Make sure request locale is taken into account when setting the active option.
