### ISSUE TITLE
[Dashboard] - avatar of the last poster is shown

### ISSUE THREAD

**Issue by thisismeonmounteverest** [BeWelcome/rox#93]
This might be confusing, since it looks like that person opened the topic

**Comment by thisismeonmounteverest** [comment]
I changed that to showing the first poster instead. But now it is unclear if the picture belongs to the member given in the small print.

@amnesiac84: Any other ideas?

**Comment by amnesiac84** [comment]
Added a wordcode 'thread.lastpostby' to emphasize it's the last post and to allow translation
